version: '3'
volumes:
  pgdata:
services:
  pivit-store-db:
    build: ./db
    container_name: pivit-store-db
    command: -c 'listen_addresses="*"'
    environment:
      - POSTGRES_USER=pivit_store
      - POSTGRES_PASSWORD=9d2c3fnCsXeU
      - POSTGRES_DB=pivit_store_db
    restart: on-failure
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - store-api

networks:
  store-api: